server:
 servlet:
    context-path: /produdoro/api
    
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb+srv://maabiadev:19872007@cluster0.oypmg.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      auto-index-creation: true      

springdoc:
  swagger-ui:
    path: /swagger
